# Random module is imported to generate random numbers
import random
x = random.randint(1,50)
print("\nYou've only 6 chances to guess the integer!\n")
# Count is declared to count the number of attempts
count = 0
# The loop is run 6 time and every time the user enters the number it is compared with the random number generated by the random module and the output is shown accordingly.
while count < 6:
    count += 1
    guess = int(input("Guess a number:- "))
    if x == guess:
        print("Congratulations you guessed it in",count, " try")
        break
    elif x > guess:
        print("Guessed a bigger number!")
    elif x < guess:
        print("Guessed a smaller number!")
if count >= 6:
    print("\nThe number is %d" % x)
    print("\tBetter Luck Next time!")
